In [48]:
import pandas as pd
data = pd.read_csv('6_Janewalk.csv')
data.head()

,id,frame,r_hip_ang,r_knee_ang,r_ankle_ang,r_elbow_ang,r_shoulder_ang,gender,age,r_hip_vel,...,r_hip_accel_2,r_knee_accel_2,r_ankle_accel_2,r_elbow_accel_2,r_shoulder_accel_2,r_hip_accel_3,r_knee_accel_3,r_ankle_accel_3,r_elbow_accel_3,r_shoulder_accel_3
0,6,1,168.123865,177.951042,108.067586,163.224523,12.874653,female,>40,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
1,6,2,167.938331,178.002006,105.509586,162.872093,13.412618,female,>40,-2.783014,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
2,6,3,167.395766,178.322374,104.910155,162.771944,13.659899,female,>40,-5.425649,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
3,6,4,166.917527,178.316548,104.612400,162.915019,13.901934,female,>40,-3.586792,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
4,6,5,166.899077,178.387432,103.615752,162.310084,13.873886,female,>40,-0.110697,...,-41.745216,11.466797,-575.550014,-79.296762,121.041978,0.0,0.0,0.0,0.0,0.0

In [60]:

context_columns = ['id','gender','age']
sequence_index = 'frame'
from sdv.timeseries import PAR

model = PAR(
#entity_columns=entity_columns,
#context_columns=context_columns,
sequence_index=sequence_index,
)

model.fit(data)

In [62]:
synthetic_data = model.sample()
synthetic_data.head()

KeyError: 'frame'

In [43]:
from sdv.evaluation import evaluate

evaluate(synthetic_data, data)

0.8461243522435012

In [44]:
evaluate(synthetic_data, data, aggregate=False)

,metric,name,raw_score,normalized_score,min_value,max_value,goal,error
0,KSComplement,Inverted Kolmogorov-Smirnov D statistic,0.692249,0.692249,0.0,1.0,MAXIMIZE,None
1,CSTest,Chi-Squared,1.000000,1.000000,0.0,1.0,MAXIMIZE,None

In [45]:
new_data = pd.concat([data, synthetic_data])
print(len(new_data.index))

10005

In [46]:
new_data.to_csv('9_RaymondwalkSynthetic.csv', index=False)